openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is the Contacts application API, which allows users to manage a list of contacts.
tags:
  - name: Contacts
    description: Endpoints for managing contacts (e.g., creating, updating, deleting)
  - name: Auth
    description: Endpoints for user authentication (e.g., login, signup, token refresh)
servers:
  - url: http://localhost:3000
  - url: https://homework-6-a5jo.onrender.com
paths:
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
